default: &default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_bin
  charset: utf8mb4
  username: root
  password: <%= ENV.fetch("SECRET_RAILS_DB_PASSWORD") %>
  host: 127.0.0.1
  port: 3306

development:
  <<: *default
  database: myperfectweekend_development

test:
  <<: *default
  database: myperfectweekend_test

production:
  <<: *default
  url: <%= ENV.fetch("DATABASE_URL") %>
